package com.distribution.modules.card.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table card_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CardInfo {
    /** */
    private String id;

    /** 银行代号*/
    private String bankNum;

    /** 信用卡代号*/
    private String cardNum;

    /** 信用卡名称*/
    private String cardName;

    /** 信用卡图片*/
    private String cardImg;

    /** 信用卡详情*/
    private String cardInfo;

    /** 信用卡办理链接*/
    private String cardUrl;

    /** */
    private String updateTime;

    /** */
    private String addTime;

    /** */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.id
     *
     * @return the value of card_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.id
     *
     * @param id the value for card_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.bank_num
     *
     * @return the value of card_info.bank_num
     *
     * @mbg.generated
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.bank_num
     *
     * @param bankNum the value for card_info.bank_num
     *
     * @mbg.generated
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_num
     *
     * @return the value of card_info.card_num
     *
     * @mbg.generated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_num
     *
     * @param cardNum the value for card_info.card_num
     *
     * @mbg.generated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_name
     *
     * @return the value of card_info.card_name
     *
     * @mbg.generated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_name
     *
     * @param cardName the value for card_info.card_name
     *
     * @mbg.generated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_img
     *
     * @return the value of card_info.card_img
     *
     * @mbg.generated
     */
    public String getCardImg() {
        return cardImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_img
     *
     * @param cardImg the value for card_info.card_img
     *
     * @mbg.generated
     */
    public void setCardImg(String cardImg) {
        this.cardImg = cardImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_info
     *
     * @return the value of card_info.card_info
     *
     * @mbg.generated
     */
    public String getCardInfo() {
        return cardInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_info
     *
     * @param cardInfo the value for card_info.card_info
     *
     * @mbg.generated
     */
    public void setCardInfo(String cardInfo) {
        this.cardInfo = cardInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_url
     *
     * @return the value of card_info.card_url
     *
     * @mbg.generated
     */
    public String getCardUrl() {
        return cardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_url
     *
     * @param cardUrl the value for card_info.card_url
     *
     * @mbg.generated
     */
    public void setCardUrl(String cardUrl) {
        this.cardUrl = cardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.update_time
     *
     * @return the value of card_info.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.update_time
     *
     * @param updateTime the value for card_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.add_time
     *
     * @return the value of card_info.add_time
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.add_time
     *
     * @param addTime the value for card_info.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.is_delete
     *
     * @return the value of card_info.is_delete
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.is_delete
     *
     * @param isDelete the value for card_info.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}