package com.distribution.modules.account.entity;

import lombok.Data;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table member_account_histroy
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class MemberAccountHistory {
    /** */
    private String id;

    /** 收入类型，0:支出,1:收入*/
    private Boolean hisType;

    /** 关联的订单ID*/
    private String orderId;

    /** */
    private BigDecimal hisAmount;

    /** */
    private String hisNote;

    /** */
    private String isDelete;

    /** */
    private String addTime;

    /** */
    private String updateTime;

}