package com.distribution.modules.dis.dao;

import com.distribution.modules.dis.entity.DisFans;

import java.util.List;
import java.util.Map;

public interface DisFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_fans
     *
     * @mbg.generated
     */
    int insert(DisFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_fans
     *
     * @mbg.generated
     */
    int insertSelective(DisFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_fans
     *
     * @mbg.generated
     */
    DisFans selectByPrimaryKey(String id);

    /**
     * 查询列表
     * @param param
     * @return
     */
    List<DisFans> selectList(Map<String, Object> param );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisFans record);

    /**
     * 批量删除
     * @param ids
     */
    void deleteBatch(String[] ids);
}