package com.distribution.modules.dis.dao;

import com.distribution.modules.dis.entity.DisProfiParam;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface DisProfiParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profi_param
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profi_param
     *
     * @mbg.generated
     */
    int insert(DisProfiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profi_param
     *
     * @mbg.generated
     */
    int insertSelective(DisProfiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profi_param
     *
     * @mbg.generated
     */
    DisProfiParam selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profi_param
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DisProfiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profi_param
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DisProfiParam record);

    /**
     * 批量删除
     * @param ids
     */
    void deleteBatch(String[] ids);

    /**
     * 查询列表
     * @param map
     * @return
     */
    List<DisProfiParam> queryList(Map<String, Object> map);
}