package com.distribution.modules.account.dao;


import com.distribution.modules.account.entity.MemberAccountHistory;

public interface MemberAccountHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_account_histroy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_account_histroy
     *
     * @mbg.generated
     */
    int insert(MemberAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_account_histroy
     *
     * @mbg.generated
     */
    int insertSelective(MemberAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_account_histroy
     *
     * @mbg.generated
     */
    MemberAccountHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_account_histroy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_account_histroy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberAccountHistory record);
}