package com.distribution.modules.dis.entity;

import lombok.Data;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dis_fans
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class DisFans {
    /** */
    private String id;

    /**
     * 关联的推荐人ID
     */
    private DisMemberInfoEntity disMemberInfo;

    /**
     * 微信ID
     */
    private String wechatId;

    /**
     * 微信头像
     */
    private String wechatImg;

    /**
     * 微信昵称
     */
    private String wechatNickname;

}